server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

open:
  api:
    info:
      title: Account Service
      version: v1.0
      description: Document for Account Service
    servers:
      - url: http://localhost:8081
        description: local
      - url: http://localhost:8080/accounts
        description: gateway
